### ISSUE TITLE
Script returns empty list of links

### ISSUE THREAD

**Issue by cyfrost** [aviaryan/Kissanime-Batch-Downloader#19]
here's what happened:
tried downloading one piece episodes from `kissanime.ru` on `GoogleChrome` by running your script: `$.getScript("https://rawgit.com/aviaryan/Kissanime-Batch-Downloader/master/kissanime.js")`, it resulted in empty list of links.

the possible error was related to XMLHttpRequest as shown below.. maybe you can relate, so attaching a screenshot below:
![capture](https://cloud.githubusercontent.com/assets/12471103/24069832/9e9619e0-0bd7-11e7-913e-141aa4b2f0e1.PNG)

any possible fix? thanks for your work.

**Comment by ghost** [comment]
I'm having the same issue. Recently learned of this awesome tool, and it seems to be the only one that updates, which is awesome. Thanks for this avia.
(I've tried replacing the script text with #16 fix for retrieving, but obviously I don't completely know what I'm doing, because it didn't work.)

**Comment by aviaryan** [comment]
@cyrusfrost @lilmrock4456 I will have a look at this issue in a couple of days. Thanks for your patience.

**Comment by cyfrost** [comment]
okay thanks!

**Comment by cyfrost** [comment]
any progress? just curious.

**Comment by aviaryan** [comment]
@cyrusfrost See #18

**Comment by cyfrost** [comment]
triggered a js alert "Malformed UTF-8, try another browser"...ran it on firefox, said it detected a captcha needed to be solved manually, opened the redirect link in a new tab, and there was no captcha, the video played just fine.

**Comment by walidsa3d** [comment]
Same problem here: empty file.

**Comment by aviaryan** [comment]
@walidsa3d Which site? Please specify.

**Comment by walidsa3d** [comment]
@aviaryan kissanime.ru

**Comment by Roshri** [comment]
I'm having the same issue on kissasian.

**Comment by aviaryan** [comment]
@Roshri @walidsa3d Recently they have added captchas when opening a page. If that is happening on your side, this script will probably not work. 

Also, do you see the download links on the kissasian episode page @Roshri ? I have seen kiss* sites switching to openload server these days. If they have done this, download links will be removed.
