### ISSUE TITLE
WTF facebook.What is wrong with you.COPYRIGHT

### ISSUE THREAD

**Issue by nawafgantare** [aviaryan/Kissanime-Batch-Downloader#21]
so when i saw this script i was amazed by the work of the developer and i respect him for making such an awesome script .i shared it on my facebook profile and look today what i got 

http://image.prntscr.com/image/16ad0cd0327c433abc53e7e7f5b3537a.png
http://prnt.sc/en6zoz

I mean like wtf.how does this includes in copyright?

**Comment by aviaryan** [comment]
Ha ha.. Looks like someone reported this repo to facebook. 
And it doesn't seem to be reported by some Kiss* website but by some other website/download tool author who won't like this script to become popular. 😂

**Comment by nitinitleen1** [comment]
Generally the anime websites provide download links which is attached with some advertising sites through which they make money. In our case(i.e using the script) we are using another downloading tool and hence some of the sites reported this issue.

By the way It is an awesome script Avi and I loved it and  tend to use most of the time.

**Comment by phanirithvij** [comment]
Well the issue is closed ?

  I mean why wasn't this issue closed?
