### ISSUE TITLE
KissAnime problems reports

### ISSUE THREAD

**Issue by aviaryan** [aviaryan/Kissanime-Batch-Downloader#3]
This issue will contain logs of problems encountered with the KissAnime website. These problems will be cause due to changes in the website.

----

10-2-17 --- Captcha has been added on the KissAnime website which doesn't allow quick successive opening on episode pages. So the script fails to fetch more than N (6 to 8) number of links in one go. 

UPDATE: 10-2-17 14:34 IST --- Captcha has been removed now. Everything is working.

**Comment by ceesvanegmond** [comment]
@aviaryan Executing ```$.getScript("https://rawgit.com/aviaryan/Kissanime-Batch-Downloader/master/kissanime.js")``` on ```http://kissanime.ru/Anime/Fate-stay-night``` results in an empty links.txt file. Tried chrome and safari, same result.

**Comment by aviaryan** [comment]
@ceesvanegmond The script works perfectly for me. I just generated [these links](http://pastebin.com/C7LekmC4). Btw, are you able to open any episode ([example](http://kissanime.ru/Anime/Fate-stay-night/Episode-002?id=10576))? This can happen because KissAnime sometimes puts a captcha over the user. You will have to manually bypass it.

**Comment by ceesvanegmond** [comment]
@aviaryan Ah, youre right. I get the captcha alot of times. Any way to avoid this?

**Comment by aviaryan** [comment]
@ceesvanegmond Don't know. Captcha shows for me for some times but after solving it a lot of time, it disappears and won't bother me again. Btw, I am thinking of making the script captcha-aware so that users can solve the captcha and then resume the script when a captcha comes. 
Since I'm not seeing the captcha right now, so will you help me in testing it?

**Comment by ceesvanegmond** [comment]
@aviaryan I would love to help!

**Comment by aviaryan** [comment]
@ceesvanegmond Try with the following script. It will show a prompt when captcha is seen and pause the script's execution. Then you can open the link and solve the captcha. Once captcha is solved, click on OK in prompt to resume script's execution. 

https://raw.githubusercontent.com/aviaryan/Kissanime-Batch-Downloader/captcha-aware/kissanime.js

**Comment by ceesvanegmond** [comment]
@aviaryan Works awesome!

**Comment by aviaryan** [comment]
@ceesvanegmond Good to know. 🎉 But can you please elaborate. Did you see the "Captcha detected" prompt? Did you have any problems solving the captcha and then resuming back the script? 
Do you think I should merge it to the master branch?

**Comment by ceesvanegmond** [comment]
@aviaryan I did see the prompt. I just had to solve the issue myself before I could continue.. That worked perfectly 👍  Didn't have any problems, worked out of the box! I think it's OK to merge with master, as it is 100% backwards compatible, don't you think?

**Comment by aviaryan** [comment]
@ceesvanegmond Thanks for your feedback. I have merged the improvements to master. #6

**Comment by aviaryan** [comment]
Closing as I don't think this issue is needed now.
