### ISSUE TITLE
Script for other kiss websites

### ISSUE THREAD

**Issue by Louise789** [aviaryan/Kissanime-Batch-Downloader#8]
Can you make one for other kiss websites? Specially kissasian? I used your script for kissasian but it only gives me empty links :( And thank you for making a batch downloader!

**Comment by aviaryan** [comment]
Hey, I just created a script for Kissasian and it is working on my end. Please try it and let me know.
https://github.com/aviaryan/Kissanime-Batch-Downloader/blob/all-kiss/kissasian.js

I am also planning to create script for KissCartoon.
You can track the progress at https://github.com/aviaryan/Kissanime-Batch-Downloader/tree/all-kiss

**Comment by aviaryan** [comment]
@Louise789 I have added support for other Kiss websites now. Please check the repo homepage.

**Comment by Louise789** [comment]
Thank you so much! It works perfectly fine for me! (All kiss scripts that you've created) @aviaryan
